name: Mobile (Expo) CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/mobile.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/mobile.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npm install -g expo-cli eas-cli
      
      - name: Login to Expo
        run: |
          cd frontend
          echo "${{ secrets.EXPO_TOKEN }}" | expo login --non-interactive
      
      - name: Lint
        run: |
          cd frontend
          npm run lint
      
      - name: Build preview
        if: github.event_name == 'pull_request'
        run: |
          cd frontend
          eas build --platform all --profile preview --non-interactive
      
      - name: Build production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd frontend
          eas build --platform all --profile production --non-interactive
      
      - name: Submit to stores
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd frontend
          eas submit --platform all --latest