name: Web CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'stoic-mentor/**'
      - '!stoic-mentor/backend/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'stoic-mentor/**'
      - '!stoic-mentor/backend/**'
      - '.github/workflows/web.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'stoic-mentor/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd stoic-mentor
          npm ci
      
      - name: Lint
        run: |
          cd stoic-mentor
          npm run lint
      
      - name: Build
        run: |
          cd stoic-mentor
          npm run build

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./stoic-mentor
          vercel-args: '--prod' 